spring.application.name=foodrescue-api

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/foodrescuedb
# For production, you can use:
# spring.data.mongodb.uri=mongodb+srv://<username>:<password>@cluster0.mongodb.net/foodrescuedb

# Server
server.port=8080

# # H2 Console Configuration
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
# spring.h2.console.settings.web-allow-others=true

# # Datasource Configuration (H2 In-Memory)
# spring.datasource.url=jdbc:h2:mem:foodrescuedb;DB_CLOSE_DELAY=-1
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=password

# # JPA / Hibernate
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=deykrunal71@gmail.com
spring.mail.password=pdyx hias qoxg bejs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
